### ISSUE TITLE
加入这个mod导致了其他人无法通过局域网联机

### ISSUE THREAD

**Issue by NEFirefox** [cm6744/TechnicalEngineering3-1.18.2#2]
会出现：Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
的提示框，导致其他人加不进去局域网联机服务器
如果需要mod列表和log文件，我在mcbbs上发过帖子：
https://www.mcbbs.net/forum.php?mod=viewthread&tid=1446421
希望能够解决（
我猜测是这个mod和一堆其他的mod有混淆类型的冲突导致了指针失控

**Comment by cm6744** [comment]
已修复
